name: Run Fooocus on CPU

on:
  workflow_dispatch:
  push:

jobs:
  run-fooocus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Use uma versão compatível do Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygit2==1.15.1 packaging  # Instale pacotes necessários
          pip install -r Fooocus/requirements_versions.txt  # Instale as dependências do Fooocus

      - name: Set environment variable to use CPU
        run: |
          echo "CUDA_VISIBLE_DEVICES=" >> $GITHUB_ENV  # Adiciona variável de ambiente para garantir que a CPU seja usada

      - name: Run Fooocus
        run: |
          cd Fooocus
          python entry_with_update.py --share --always-high-vram  # Execute seu script principal
